const FilterData = {
    FilterData :[
        {
            "brandImg":"https://cdn.tgdd.vn/Brand/1/logo-iphone-220x48.png",
            "data":"iphone",
            "name":"iPhone"
        },
        {
            "brandImg":"https://cdn.tgdd.vn/Brand/1/samsungnew-220x48-1.png",
            "data":"samsung",
            "name":"SamSung"
        },
        {
            "brandImg":"https://cdn.tgdd.vn/Brand/1/OPPO42-b_5.jpg",
            "data":"oppo",
            "name":"OPPO"
        },
        {
            "brandImg":"https://cdn.tgdd.vn/Brand/1/vivo-logo-220-220x48-3.png",
            "data":"vivo",
            "name":"Vivo"
        },
        {
            "brandImg":"https://cdn.tgdd.vn/Brand/1/logo-xiaomi-220x48-5.png",
            "data":"xiaomi",
            "name":"Xiaomi"
        },
        {
            "brandImg":"https://cdn.tgdd.vn/Brand/1/Realme42-b_37.png",
            "data":"realme",
            "name":"Realme"
        },
        {
            "brandImg":"https://cdn.tgdd.vn/Brand/1/Nokia42-b_21.jpg",
            "data":"nokia",
            "name":"Nokia"
        },
        {
            "brandImg":"https://cdn.tgdd.vn/Brand/1/tcl-logo-lon-220x48.jpg",
            "data":"tcl",
            "name":"TCL"
        },
        {
            "brandImg":"https://cdn.tgdd.vn/Brand/1/Itel42-b_54.jpg",
            "data":"itel",
            "name":"Itel"
        },
        {
            "brandImg":"https://cdn.tgdd.vn/Brand/1/Masstel42-b_0.png",
            "data":"masstel",
            "name":"Masstel"
        },
    ]
}